name: node Continous Integration
on: push
jobs: 
    build-node:
        name: Build Node
        runs-on: ubuntu-latest
        container: node:24
        steps:
            - run: node --version
            - run: npm --version
            - run: npm install

